const COLLECTION_NAME = [
    'BRAND',
    'CATEGORY',
    'CUSTOMER',
    'EMPLOYEE',
    'EXPORT_ORDER_DETAIL',
    'EXPORT_ORDER',
    'IMPORT_ORDER_DETAIL',
    'IMPORT_ORDER',
    'PAYMENT',
    'PERMISSION',
    'ROLE',
    'SUPPLIER',
    'WAREHOUSE',
    'PRODUCT'
]

PERMISSION_TITLE_ENUM = []
COLLECTION_NAME.forEach(name => {
    PERMISSION_TITLE_ENUM.push(`READ_${name}`)
    PERMISSION_TITLE_ENUM.push(`CREATE_${name}`)
    PERMISSION_TITLE_ENUM.push(`UPDATE_${name}`)
    PERMISSION_TITLE_ENUM.push(`DELETE_${name}`)

})
module.exports = {
    PERMISSION_TITLE_ENUM
}